[package]
name = "safedotenv"
version = "0.1.0"
authors = ["gbaranski <gbaranski19@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
structopt = "0.3.21"
human-panic = "1.0.3"
